### ISSUE TITLE
현재 접속자, 서버 동작중인 여부 확인 스크립트 작성

### ISSUE THREAD

**Issue by bomberman03** [BCSDLab/Timetable#11]
VPS로 SSH 접속 했을 때 상태 확인용 스크립트

1. 현재 접속자 현황
2. 현재 구동중인 노드 서버 현황

보상: 뿌듯함

**Comment by tibyte** [comment]
/home/grade4/status.sh 작성
각자의 홈디렉터리에 있는 .bash_profile에서 접속 시 실행

알 수 있는 정보
- 현재 접속자 현황
- node 구동 여부
- npm 구동 여부

![-1](https://cloud.githubusercontent.com/assets/15897077/15673194/0ed80648-2770-11e6-8f79-b30fc4dd4637.png)
