### ISSUE TITLE
postman API error

### ISSUE THREAD

**Issue by YunZz** [BCSDLab/Timetable#5]
retrun unexpected token

**Comment by bomberman03** [comment]
<img width="960" alt="postman form-data" src="https://cloud.githubusercontent.com/assets/12102711/15561329/91a9bf98-232f-11e6-9157-ffc3a6c183ea.png">
<img width="960" alt="node form-data" src="https://cloud.githubusercontent.com/assets/12102711/15561325/84eb2058-232f-11e6-8d0c-0e24374897c7.png">
<img width="960" alt="postman x-www-form-urlencoded" src="https://cloud.githubusercontent.com/assets/12102711/15561333/9bdd1e92-232f-11e6-91f4-24acc593a89e.png">
<img width="960" alt="node x-www-form-urlencoded" src="https://cloud.githubusercontent.com/assets/12102711/15561335/a21ae92e-232f-11e6-8881-bdee71eb59d0.png">

form-data 과 x-www-form-urlencoded 에 대한 비교
https://gist.github.com/jays1204/703297eb0da1facdc454

**Comment by YunZz** [comment]
![image](https://cloud.githubusercontent.com/assets/15630272/15561516/c082323a-2331-11e6-9027-0a33adad3d12.png)


browser에서 application/json으로 보낸것처럼 post맨에서도 application/json으로 보냈을경우에는 왜 unexpected token u가 리턴될까요?

**Comment by bomberman03** [comment]
흠 그건 한번 살펴봐야 알 거 같은데 ㅎㅎ 정 안되면 와이어 샤크로 패킷 까보지 한번 까보는 것도 재밌는 활동이 될 것 같음 ㅋㅋ
