### ISSUE TITLE
class User

### ISSUE THREAD

**Issue by EunBeeJo** [BCSDLab/Timetable#6]
class User{
   String email; //user id
   String password;
   String device;
   String location; //현재 위치
   boolean login_status; // login 상태
}
----> User 구분
회원가입 : User Create
로그인 : User data Read
한번 로그인 이후 :  로그인 된 device에서 App 실행시 User data read
로그아웃 : login_status = false;
회원탈퇴 : User data Delete
콜밴방(?)에 참여 후 현재 위치를 다른 멤버에게 알릴 때 사용

이렇게 남기면되는건가요????!

**Comment by bomberman03** [comment]
굳

**Comment by bomberman03** [comment]
API 구현이 완료되었다면 이슈를 닫아주세요

**Comment by YunZz** [comment]
완성
