### ISSUE TITLE
class RoomData

### ISSUE THREAD

**Issue by EunBeeJo** [BCSDLab/Timetable#7]
class RoomData{
   String startLocation; //출발 장소
   String arriveLocation; //도착 장소
   String startTime; //출발 시간
   int minMember; //최소인원
   int presentMember; //현재 인원
   bool start; //start 여부
   Crew crew; // 방에 참여한 사람 정보
}

---------->
 * 방만들기 Create
 * Crew가 참여하면 방정보 Read. Crew의 화면에 띄워줌
 * 현재 인원이 바뀔 때 마다 presentMember Update
 * 모든 인원이 방을 나가거나 Crew들이 목적지에 도착하면 Delete

**Comment by EunBeeJo** [comment]
int room number; //방 구분
이거 추가할게요

**Comment by bomberman03** [comment]
API 구현이 완료 되었다면 이슈를 닫아주세요

**Comment by YunZz** [comment]
완성
